### ISSUE TITLE
[Bug] Resave of templates where there is whitelist doesn't work

### ISSUE THREAD

**Issue by gizellos** [rafaelgs18/ESGST#71]
Let's say I have a template with Whitelist and some groups. I enable the template, uncheck the whitelist and click to Save Template. I keep the name because I just want to update the template. Then I normally click to Save as I am supposed to do.

The template doesn't update.

**Comment by CaitSith2** [comment]
A real annoying issue, because sometimes I want the GA to be group exclusive, without my whitelist, for cases where I am wanting to balance it out so that more of the group members win.

**Comment by ldeman** [comment]
it is an annoyance, but it also really isn't all too hard to load the profile with the checkbox then immediately click the x-mark to remove it, make the changes then re-save it as the original name.

too clarify i don't mean it doesn't need a fix,  it clearly could use one.  i just mean it's not a super urgent one.
