### ISSUE TITLE
[Bug] Moved/moving element after last update

### ISSUE THREAD

**Issue by gizellos** [rafaelgs18/ESGST#74]
There is free space on the left side at the top of main page. After I scroll up, the search box will move. 

![moving element](https://cloud.githubusercontent.com/assets/2397851/24121100/4e02557a-0db7-11e7-9d20-0c5e1cc69faa.gif)

**Comment by ldeman** [comment]
that's and issue with ad-blocker not fully blocking an ad.  not this script. xD
![image](https://cloud.githubusercontent.com/assets/10275898/24121188/64253c0a-0d85-11e7-96f6-1ab63c8724b0.png)

**Comment by gizellos** [comment]
OK, it's possible.

**Comment by ldeman** [comment]
i had that issue about a week ago on most refreshes.  occasionally it would go away like ublock was supposed to make it, but i gave up fighting it and just enabled ads on SG personally.

**Comment by gizellos** [comment]
I solved it manual blocking the element.

**Comment by gizellos** [comment]
BTW: can I delete or lock my own issues?

**Comment by ldeman** [comment]
yeah, i suppose this could be turned into a "feature request" as in "ad-blocker" but.. idk how "insert new name here" would feel about it.

- should be below or next to the comment button on your own threads.

**Comment by gizellos** [comment]
Oh, yes, thanks.
