### ISSUE TITLE
show supported operating systems

### ISSUE THREAD

**Issue by alexanderadam** [rafaelgs18/ESGST#78]
Wow, the Script is wonderful!
It would just be perfect if the supported Operating Systems of a Game would be shown as well.

**Comment by ldeman** [comment]
i highly recommend ruphines [SG Tags](https://www.steamgifts.com/discussion/l6RDh/userscript-sg-game-tags-show-some-info-of-the-game-cards-achievement-bundled-etc) for those types of tag.
![image](https://cloud.githubusercontent.com/assets/10275898/24248215/9024c7c6-0f9c-11e7-8387-8b2f81201045.png)

**Comment by alexanderadam** [comment]
This is awesome, thank you @ldeman!

**Comment by rafaelgs18** [comment]
Yep, that's a great script for that already, so labeling this as "wontfix" meaning "wontimplement".
