### ISSUE TITLE
[Bug] GAs description in popup is aligned to the center

### ISSUE THREAD

**Issue by gizellos** [rafaelgs18/ESGST#81]
The text in giveaway description popup is aligned to the center although the original align is to the left. It can cause quite trouble if there are some lists as you can see in the attached image.

![bad align](https://cloud.githubusercontent.com/assets/2397851/24472564/736bfcd8-14c6-11e7-84ef-e54f5a0fd862.png)

**Comment by gizellos** [comment]
And centered text is right-aligned. :-O

![2017-03-31_165934](https://cloud.githubusercontent.com/assets/2397851/24556103/93e20b88-1633-11e7-9d91-9528dc2b1b7b.png)
![2017-03-31_165952](https://cloud.githubusercontent.com/assets/2397851/24556106/96f91604-1633-11e7-95af-f9bafa6ff7ce.png)

**Comment by gizellos** [comment]
But the text should not be even centered in the first place, right? Coz it is not possible to align text on SG, is it? I am kinda confused of all this.

**Comment by ldeman** [comment]
correct it should not be centere, and also correct it's not possible for users to align text.  however that description popout is causing it to 'appear as if' it was aligned in those ways is what they mean.

it may be as simple as you aligning stuff to the left by one alignment to correct it, but idk how that would pan out for stuff already aligned to the far left.
