### ISSUE TITLE
[Bug] Unable to change/disable sync

### ISSUE THREAD

**Issue by frostypancake** [rafaelgs18/ESGST#82]
All of the settings on the settings page seem to save except for the auto-sync.  It defaults to 7 and will not save, no matter what I change it to.  Using the latest version of firefox.

**Comment by rafaelgs18** [comment]
Weird, here it is saving. Any errors in the console?

**Comment by frostypancake** [comment]
18:33:59.978 WBCButton is undefined 1 rhSGST.user.js:3657:9
That error pops up[ when the settings page is loaded.

18:36:42.278 Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. 1 jquery-1.6.min.js:16:34882
It shows that when I click on the dropdown menu to change it from 7.

**Comment by rafaelgs18** [comment]
I cannot reproduce this. Do you have the latest version and does it happen with other userscripts disabled?

**Comment by frostypancake** [comment]
version 4.21.3
firefox 52.02 (32bit)

I disabled all add-ons and all other scripts and it still would not work.

I will try to uninstall/reinstall the script.

**Comment by rafaelgs18** [comment]
Updates from rhSGST to ESGST had to be made mostly manually, as far as I'm aware. And Greasemonkey is specially picky about that. On Tampermonkey you can just edit the metadata header and it will update normally.

I hope you didn't lose any data by uninstalling 4.21.3, you could have told me it installed side by side and I could have helped you make sure it properly updated.
