### ISSUE TITLE
Reviews are not shown in endless scrolling after page 1

### ISSUE THREAD

**Issue by havrancek** [rafaelgs18/ESGST#84]
Hello,
title says it all. There´s possibility to see reviews (xx%) on main SG page & saves a click inside the game,
but with endless scrolling turned on, it is not working, there´s an empty space.
Can it be fixed, pls?
Thx in advance

**Comment by rafaelgs18** [comment]
Reviews? Do you mean winning chance? Weird, no one has reported this yet.

**Comment by havrancek** [comment]
[http://imgur.com/vx39Y6y](url)

**Comment by rafaelgs18** [comment]
That's neither from this script nor native from SG. I don't offer endless scrolling support for features of other scripts anymore. You can ask the creator of that script to add endless scrolling support to their script.

**Comment by havrancek** [comment]
oh, my bad, sorry
