### ISSUE TITLE
[Bug] Save template button doesnt show

### ISSUE THREAD

**Issue by Mieekaserra** [rafaelgs18/ESGST#86]
On giveaway page, if extended steam gifts is enabled, the "save template" button hides itself.

**Comment by ldeman** [comment]
pure curiosity question,  what does extended steam gifts have that ESGST doesn't have that makes it needed?

**Comment by gizellos** [comment]
I think you can remove ESG now since ESGST already has all the important functions. You will have less problems with incompatibility then. I did the same some time ago and I am very satisfied.

**Comment by rafaelgs18** [comment]
Incompatibilities with other scripts aren't bugs and I stopped adding support to Extended SteamGifts long ago.
