### ISSUE TITLE
error link?!

### ISSUE THREAD

**Issue by tigerelfe** [rafaelgs18/ESGST#88]
hey :3
i really love your addon
at least, since i found out how to use some parts of it xD

but the last update brought a problem
it shows [this](https://imgur.com/a/kH5yZ) and when clicking ok i come to this installation page and click new installation .. but then that page just closes
and that repeats on every new GA page i open and gets a bit annoying now :3
i am really a noob when it comes to those scripts etc
i could probably just uninstall the version i have and re-install it .. but then my saved stuff would be gone :D

well yeah ... hope i could make myself clear -.-'

thanks and greetings :3

**Comment by Royalgamer06** [comment]
Do what it says :)
Remove this script: https://greasyfork.org/en/scripts/25920-steamgifts-giveaway-error-link/

**Comment by tigerelfe** [comment]
xD
works now
didnt even know i had a script with that name :D
thank you :3
